# Basic data types

### Numbers: Integers and floats work as you would expect from other languages:

In [6]:
x = 3
print(type(x)) # Prints "<class 'int'>"
print(x)       # Prints "3"
print(x + 1)   # Addition; prints "4"
print(x - 1)   # Subtraction; prints "2"
print(x * 2)   # Multiplication; prints "6"
print(x ** 2)  # Exponentiation; prints "9"
x += 1
print(x)  # Prints "4"
x *= 2
print(x)  # Prints "8"
y = 2.5
print(type(y)) # Prints "<class 'float'>"
print(y, y + 1, y * 2, y ** 2) # Prints "2.5 3.5 5.0 6.25"

<class 'int'>
3
4
2
6
9
4
8
<class 'float'>
2.5 3.5 5.0 6.25


### Booleans: Python implements all of the usual operators for Boolean logic, but uses English words rather than symbols (&&, ||, etc.):

In [5]:
t = True
f = False
print(type(t)) # Prints "<class 'bool'>"
print(t and f) # Logical AND; prints "False"
print(t or f)  # Logical OR; prints "True"
print(not t)   # Logical NOT; prints "False"
print(t != f)  # Logical XOR; prints "True"

<class 'bool'>
False
True
False
True


### Strings: Python has great support for strings:

In [7]:
hello = 'hello'    # String literals can use single quotes
world = "world"    # or double quotes; it does not matter.
print(hello)       # Prints "hello"
print(len(hello))  # String length; prints "5"
hw = hello + ' ' + world  # String concatenation
print(hw)  # prints "hello world"
hw12 = '%s %s %d' % (hello, world, 12)  # sprintf style string formatting
print(hw12)  # prints "hello world 12"

hello
5
hello world
hello world 12


### String objects have a bunch of useful methods

In [8]:
s = "hello"
print(s.capitalize())  # Capitalize a string; prints "Hello"
print(s.upper())       # Convert a string to uppercase; prints "HELLO"
print(s.rjust(7))      # Right-justify a string, padding with spaces; prints "  hello"
print(s.center(7))     # Center a string, padding with spaces; prints " hello "
print(s.replace('l', '(ell)'))  # Replace all instances of one substring with another;
                                # prints "he(ell)(ell)o"
print('  world '.strip())  # Strip leading and trailing whitespace; prints "world"

Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world


# Containers

## Lists

### A list is the Python equivalent of an array, but is resizeable and can contain elements of different types:

In [9]:
xs = [3, 1, 2]    # Create a list
print(xs, xs[2])  # Prints "[3, 1, 2] 2"
print(xs[-1])     # Negative indices count from the end of the list; prints "2"
xs[2] = 'foo'     # Lists can contain elements of different types
print(xs)         # Prints "[3, 1, 'foo']"
xs.append('bar')  # Add a new element to the end of the list
print(xs)         # Prints "[3, 1, 'foo', 'bar']"
x = xs.pop()      # Remove and return the last element of the list
print(x, xs)      # Prints "bar [3, 1, 'foo']"

[3, 1, 2] 2
2
[3, 1, 'foo']
[3, 1, 'foo', 'bar']
bar [3, 1, 'foo']


### Slicing: In addition to accessing list elements one at a time, Python provides concise syntax to access sublists

In [10]:
nums = list(range(5))     # range is a built-in function that creates a list of integers
print(nums)               # Prints "[0, 1, 2, 3, 4]"
print(nums[2:4])          # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(nums[2:])           # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print(nums[:2])           # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(nums[:])            # Get a slice of the whole list; prints "[0, 1, 2, 3, 4]"
print(nums[:-1])          # Slice indices can be negative; prints "[0, 1, 2, 3]"
nums[2:4] = [8, 9]        # Assign a new sublist to a slice
print(nums)               # Prints "[0, 1, 8, 9, 4]"

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


### Loops: You can loop over the elements of a list like this:

In [16]:
animals = ['cat', 'dog', 'monkey']

## (1) loop over the elements of a list
for animal in animals:
    print(animal)                        # Prints "cat", "dog", "monkey", each on its own line.
    
## (2) If you want access to the index of each element within the body of a loop, use the built-in enumerate function:
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx + 1, animal)) # Prints "#1: cat", "#2: dog", "#3: monkey", each on its own line
    

cat
dog
monkey
#1: cat
#2: dog
#3: monkey


## Dictionaries

### A dictionary stores (key, value) pairs, similar to a Map in Java or an object in Javascript. You can use it like this:

In [13]:
d = {'cat': 'cute', 'dog': 'furry'}  # Create a new dictionary with some data
print(d['cat'])       # Get an entry from a dictionary; prints "cute"
print('cat' in d)     # Check if a dictionary has a given key; prints "True"
d['fish'] = 'wet'     # Set an entry in a dictionary
print(d['fish'])      # Prints "wet"
# print(d['monkey'])  # KeyError: 'monkey' not a key of d
print(d.get('monkey', 'N/A'))  # Get an element with a default; prints "N/A"
print(d.get('fish', 'N/A'))    # Get an element with a default; prints "wet"
del d['fish']         # Remove an element from a dictionary
print(d.get('fish', 'N/A')) # "fish" is no longer a key; prints "N/A"

cute
True
wet
N/A
wet
N/A


### Loops: It is easy to iterate over the keys in a dictionary:

In [15]:
d = {'person': 2, 'cat': 4, 'spider': 8}

for animal in d:
    legs = d[animal]
    print('A %s has %d legs' % (animal, legs)) # Prints "A person has 2 legs", "A cat has 4 legs", "A spider has 8 legs"

for animal, legs in d.items():
    print('A %s has %d legs' % (animal, legs)) # Prints "A person has 2 legs", "A cat has 4 legs", "A spider has 8 legs"
    

A person has 2 legs
A cat has 4 legs
A spider has 8 legs
A person has 2 legs
A cat has 4 legs
A spider has 8 legs


## Sets

### A set is an unordered collection of distinct elements.

In [19]:
animals = {'cat', 'dog'}
print('cat' in animals)   # Check if an element is in a set; prints "True"
print('fish' in animals)  # prints "False"
animals.add('fish')       # Add an element to a set
print('fish' in animals)  # Prints "True"
print(len(animals))       # Number of elements in a set; prints "3"
animals.add('cat')        # Adding an element that is already in the set does nothing
print(len(animals))       # Prints "3"
animals.remove('cat')     # Remove an element from a set
print(len(animals))       # Prints "2"

True
False
True
3
3
2


### Loops: Iterating over a set has the same syntax as iterating over a list; however since sets are unordered, you cannot make assumptions about the order in which you visit the elements of the set:

In [20]:
animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx + 1, animal))
# Prints "#1: fish", "#2: dog", "#3: cat"

#1: fish
#2: cat
#3: dog


### comprehensions

In [26]:
## transform one type of data into another
nums = [0, 1, 2, 3, 4]

## (1) List comprehensions
squares = []
for x in nums:
    squares.append(x ** 2)
print(squares)                           # Prints [0, 1, 4, 9, 16]

simple_squares = [x ** 2 for x in nums]
print(simple_squares)                    # Prints [0, 1, 4, 9, 16]

even_squares = [x ** 2 for x in nums if x % 2 == 0]
print(even_squares)                      # Prints "[0, 4, 16]"


## (2) Dictionary comprehensions:
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
print(even_num_to_square)                # Prints "{0: 0, 2: 4, 4: 16}"


## (3) Set comprehensions:
from math import sqrt
nums = {int(sqrt(x)) for x in range(30)}
print(nums)                             # 제곱근 Prints "{0, 1, 2, 3, 4, 5}"

print( sqrt(30) )


[0, 1, 4, 9, 16]
[0, 1, 4, 9, 16]
[0, 4, 16]
{0: 0, 2: 4, 4: 16}
{0, 1, 2, 3, 4, 5}
5.477225575051661


## Tuples

### A tuple is an (immutable) ordered list of values. A tuple is in many ways similar to a list; one of the most important differences is that tuples can be used as keys in dictionaries and as elements of sets, while lists cannot. Here is a trivial example:

In [27]:
d = {(x, x + 1): x for x in range(10)}  # Create a dictionary with tuple keys
print(d)          # {(0, 1): 0, (1, 2): 1, (2, 3): 2, (3, 4): 3, (4, 5): 4, (5, 6): 5, (6, 7): 6, (7, 8): 7, (8, 9): 8, (9, 10): 9}

t = (5, 6)        # Create a tuple
print(type(t))    # Prints "<class 'tuple'>"

print(d[t])       # Prints "5"
print(d[(1, 2)])  # Prints "1"

{(0, 1): 0, (1, 2): 1, (2, 3): 2, (3, 4): 3, (4, 5): 4, (5, 6): 5, (6, 7): 6, (7, 8): 7, (8, 9): 8, (9, 10): 9}
<class 'tuple'>
5
1


# Functions

### Python functions are defined using the def keyword.

In [30]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print(sign(x))        # Prints "negative", "zero", "positive"

negative
zero
positive


In [31]:
## take optional keyword arguments
def hello(name, loud=False):
    if loud:
        print('HELLO, %s!' % name.upper())
    else:
        print('Hello, %s' % name)

hello('Bob')              # Prints "Hello, Bob"
hello('Fred', loud=True)  # Prints "HELLO, FRED!"

Hello, Bob
HELLO, FRED!


# Classes

### The syntax for defining classes in Python is straightforward:

In [32]:
class Greeter(object):

    # Constructor
    def __init__(self, name):
        self.name = name  # Create an instance variable

    # Instance method
    def greet(self, loud=False):
        if loud:
            print('HELLO, %s!' % self.name.upper())
        else:
            print('Hello, %s' % self.name)

g = Greeter('Fred')  # Construct an instance of the Greeter class
g.greet()            # Call an instance method; prints "Hello, Fred"
g.greet(loud=True)   # Call an instance method; prints "HELLO, FRED!"

Hello, Fred
HELLO, FRED!


# Numpy 

많은 숫자 데이터를 하나의 변수에 넣고 관리 할 때 리스트는 속도가 느리고 메모리를 많이 차지하는 단점이 있다. 
배열(array)을 사용하면 적은 메모리로 데이터를 빠르게 처리할 수 있다. 

배열은 리스트와 비슷하지만 다음과 같은 점에서 다르다.

1. 모든 원소가 같은 자료형이어야 한다.
2. 원소의 갯수를 바꿀 수 없다.

파이썬은 자체적으로 배열 자료형을 제공하지 않는다. 따라서 배열을 구현한 다른 패키지를 임포트해야 한다. 
파이썬에서 배열을 사용하기 위한 표준 패키지는 NumPy(보통 "넘파이"라고 발음한다)이다.

numpy는 과학 계산을 위한 라이브러리로서 다차원 배열을 처리하는데 필요한 여러 유용한 기능을 제공하고 있다.
다차원의 배열 자료구조 클래스인 ndarray 클래스를 지원하며 벡터와 행렬을 사용하는 선형대수 계산에 주로 사용된다. 
내부적으로는 BLAS 라이브러리와 LAPACK 라이브러리를 사용하고 있으며 C로 구현된 CPython에서만 사용할 수 있다.

NumPy의 배열 연산은 C로 구현된 내부 반복문을 사용하기 때문에 파이썬 반복문에 비해 속도가 빠르며 벡터화 연산(vectorized operation)을 이용하여 간단한 코드로도 복잡한 선형 대수 연산을 수행할 수 있다. 또한 배열 인덱싱(array indexing)을 사용한 질의(Query) 기능을 이용하여 간단한 코드로도 복잡한 수식을 계산할 수 있다.

## Arrays

#### numpy에서 배열은 동일한 타입의 값들을 가지며, 배열의 차원을 rank 라 하고, 각 차원의 크기를 튜플로 표시하는 것을 shape 라 한다.

예를 들어, 행이 2이고 열이 3인 2차원 배열에서 rank는 2 이고, shape는 (2, 3) 이 된다.

numpy 배열을 생성하는 방법은 (1) 파이썬 리스트를 사용하는 방법과 (2) numpy에서 제공하는 함수를 사용하는 방법이 있다.

In [9]:
import numpy as np

a = np.array([1, 2, 3])   # Create a rank 1 array - 3개의 요소를 갖는 리스트를 array() 함수에 넣어 numpy 배열을 생성
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)" - 튜플에 하나의 요소만 있으면 문법상 콤마를 뒤에 붙인다.
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

# 주의할 점 : array() 안에 하나의 리스트만 들어가므로 리스트의 리스트를 넣어야 한다.
b = np.array([[1,2,3],
              [4,5,6]])            # Create a rank 2 array (2 x 3)
print(b.shape)                     # 2 x 3 array,  Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"
print(len(b), len(b[0]))           # length of rows, length of columns. prints 2 3
print(b[-1, -1])                   # 마지막 행의 마지막 열. Prints 6

d = np.array([[[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]],
              [[11,12,13,14],
               [15,16,17,18],
               [19,20,21,22]]])        # Create a rank 3 array (2 x 3 x 4)
print(len(d), len(d[0]), len(d[0][0])) # 2 3 4

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4
2 3
6
2 3 4


numpy에서 제공하는 함수를 사용하여 numpy 배열을 만드는 방법을 살펴보자. 
이러한 기능을 제공하는 함수로는 zeros(), ones(), full(), eye() 등이 있는데, zeros()는 해당 배열에 모두 0을 집어 넣고, ones()는 모두 1을 집어 넣는다. full()은 배열에 사용자가 지정한 값을 넣는데 사용하고, eye()는 대각선으로는 1이고 나머지는 0인 2차원 배열을 생성한다.

In [3]:
import numpy as np

a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

[[ 0.  0.]
 [ 0.  0.]]
[[ 1.  1.]]
[[7 7]
 [7 7]]
[[ 1.  0.]
 [ 0.  1.]]
[[ 0.62778522  0.68891022]
 [ 0.34656564  0.79197449]]


## Array indexing

In [20]:
import numpy as np

# Create the following rank 2 array with shape (2, 4)
#[[0 1 2 3]
# [4 5 6 7]]
ex = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
print(ex)
print(ex[0, :])   # 첫번째 행 전체 prints "[0 1 2 3]"
print(ex[:, 1])   # 두번째 열 전체 prints "[1 5]"
print(ex[1, 1:])  # 두번째 행의, 두번째 열부터 끝열까지 prints "[5 6 7]"
print(ex[:2, :2]) # 첫 행부터 두번째 행까지의, 첫 열부터 두번째 열까지 
                  # prints [[0 1]
                  #         [4 5]]

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"




# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

[[0 1 2 3]
 [4 5 6 7]]
[0 1 2 3]
[1 5]
[5 6 7]
[[0 1]
 [4 5]]
2
77
[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[77  6 10] (3,)
[[77]
 [ 6]
 [10]] (3, 1)


### Integer array indexing: 

#### When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array.

In [21]:
import numpy as np

# An example of integer array indexing.
lst = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
]
a = np.array(lst)
s = a[[0, 2], [1, 3]] # 정수 인덱싱 :  a[0, 1] 과 a[2, 3] 등 2개의 배열요소를 가리킨다.
print(s)              # prints "[2 12]"



b = np.array([[1, 2], [3, 4], [5, 6]])

# The returned array will have shape (3,) and
print(b[[0, 1, 2], [0, 1, 0]])  #  a[0, 0] 과 a[1, 1], a[2, 0] 등 3개의 배열요소를 가리킨다. Prints "[1 4 5]"
# The above example of integer array indexing is equivalent to this:
print(np.array([b[0, 0], b[1, 1], b[2, 0]]))  # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same element from the source array:
print(b[[0, 0], [1, 1]])  # Prints "[2 2]"
# Equivalent to the previous integer array indexing example
print(np.array([b[0, 1], b[0, 1]]))  # Prints "[2 2]"

[ 2 12]
[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [22]:
import numpy as np

# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)  # prints "array([[ 1,  2,  3],
          #                [ 4,  5,  6],
          #                [ 7,  8,  9],
          #                [10, 11, 12]])"
            
# Create an array of indices
b = np.array([0, 2, 0, 1])
# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # a[0, 0] 과 a[1, 2], a[2, 0], a[3, 1] 등 4개의 배열요소를 가리킨다. 
                           # Prints "[ 1  6  7 11]"

# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10
print(a)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


### Boolean array indexing

#### Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition.

배열 각 요소의 선택여부를 True, False로 표현하는 방식이다. 
만약 배열 a 가 2 x 3 의 배열이이라면, boolean 인덱싱을 정의하는 numpy 배열도 2 x 3 으로 만들고 선택할 배열요소에 True를 넣고 그렇지 않으면 False를 넣으면 된다. 

In [14]:
import numpy as np

lst = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
arr = np.array(lst)               # 3 x 3 배열 arr
bool_indexing_array = np.array([  # 직접 생성 <- 짝수만 뽑아내는 boolean 인덱싱 배열(numpy 배열)
    [False,  True, False],
    [True, False,  True],
    [False,  True, False]
])
 
# boolean 인덱스를 사용하여 True인 요소만 뽑아냄
n = arr[bool_indexing_array]      # 짝수 배열 n
print(n)                          # Prints "[2 4 6 8]"

[2 4 6 8]


In [15]:
import numpy as np
 
lst = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
arr = np.array(lst)
bool_indexing_array = (arr % 2 == 0)  # 배열 a 에 대해 짝수면 True, 홀수면 False 
print(bool_indexing_array)            # 출력: boolean 인덱싱 배열
                                      # [[False  True False]
                                      #  [ True False  True]
                                      #  [False  True False]]
            
# boolean 인덱스를 사용하여 True인 요소만 뽑아냄
print(arr[bool_indexing_array])       # 짝수 배열, 출력: "[2 4 6 8]"

# 더 간단한 표현
n = arr[ arr % 2 == 0 ];        # 짝수 배열 n
print(n)                        # 출력: "[2 4 6 8]"


[[False  True False]
 [ True False  True]
 [False  True False]]
[2 4 6 8]
[2 4 6 8]


In [7]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])  # 2 x 2 배열 a
bool_idx = (a > 2)   # 표현식을 사용 <- 2보다 큰 수만 뽑아내는 boolean 인덱싱 배열(numpy 배열)
                     # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

print(a[bool_idx])   # We use boolean array indexing to construct a rank 1 array
                     # consisting of the elements of a corresponding to the True values
                     # of bool_idx
                     # 2보다 큰 수의 배열, Prints "[3 4 5 6]"

print(a[a > 2])      # We can do all of the above in a single concise statement:
                     # 2보다 큰 수의 배열, Prints "[3 4 5 6]"

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]
